/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Nick.Sd' at '25.12.15 8:45' with Gradle 2.6
 *
 * @author Nick.Sd, @date 25.12.15 8:45
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void Main(String args[]){
    	System.out.println("Hello Recognition!");
    	
    	System.out.println("Some code!");
    }
}
